### ISSUE TITLE
[DOC] Can we add white background to the diagram?

### ISSUE THREAD

**Issue by nqbao** [aitomatic/openssm#3]
**Describe the bug**
My laptop theme is dark and the diagram does not have a white background, so it is very hard to read. Please check the screenshot

**To Reproduce**
Switch to dark theme on your mac

**Screenshots**
<img width="1046" alt="Screen Shot 2023-07-13 at 4 07 41 PM" src="https://github.com/aitomatic/openssm/assets/177742/07698fa0-2293-4263-a94b-f9119152ce13">

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Comment by ctn** [comment]
I don’t know how to do that. Can you help, @nqbao ? 😉

**Comment by nqbao** [comment]
how did you guys generate the diagram? was it from a tool or something?

**Comment by nqbao** [comment]
look like you are using draw.io https://github.com/aitomatic/openssm/tree/main/docs/diagrams

just save it again with white background. IIRC it should be part of the options when you export the diagram

**Comment by ctn** [comment]
I’m just kidding. I would like you to do it though. Yes, it is drawio. There is a downloadable client that will work directly on files.
